serve:
  port: 80
  browser: false
  playground: true
  endpoint: /solaredge
  playgroundTitle: Kadaster Gitea Playground

sources:
  - name: GITEA
    handler:
      jsonSchema:
        endpoint: https://git.dev.cloud.kadaster.nl/api/vi
        operationHeaders:
          Authorization: 'token {env.GITEA_TOKEN}'
        operations:
          - type: Query
            field: Organisations
            path: /orgs
            method: GET
            responseSample: ./jsons/orglistsampleresponse.json
            responseTypeName: Organisation   
          - type: Query
            field: repos
            path: /orgs/{args.orgname}/repos
            method: GET
            responseSample: ./jsons/reposampleresponse.json
            responseTypeName: Repo      
            
    transforms:
      - prefix:
          value: GITEA
          includeRootOperations: true
