serve:
  port: 80
  browser: false
  playground: true
  endpoint: /solaredge
  playgroundTitle: Kadaster Gitea Playground

sources:
  - name: GITEA
    handler:
      jsonSchema:
        endpoint: https://git.dev.cloud.kadaster.nl/api/v1
        operationHeaders:
          Authorization: 'token {env.GITEA_TOKEN}'
        operations:
          - type: Query
            field: Organisations
            path: /orgs
            method: GET
            responseSample: ./jsons/orglistsampleresponse.json
            responseTypeName: Organisation   
          - type: Query
            field: Repos
            path: /orgs/{args.orgname}/repos?page={args.page}
            method: GET
            responseSample: ./jsons/repolistsampleresponse.json
            responseTypeName: Repo    
          - type: Query
            field: Repo
            path: /orgs/{args.orgname}/repos/{args.reponame}
            method: GET
            responseSample: ./jsons/reposampleresponse.json
            responseTypeName: Repo  
            
    transforms:
      - prefix:
          value: GITEA
          includeRootOperations: true
